### ISSUE TITLE
Abstract base classes for base_storage.py

### ISSUE THREAD

**Issue by brinza888** [Cub11k/pyStorages#1]
[Check abc module ](https://docs.python.org/3/library/abc.html)

Use `ABCMeta` metaclass and mark not implemented methods with `@abstractmethod` decorator

https://github.com/Cub11k/storages/blob/7a68eb8a4cbd379c03222859a456ecec13b5b6ce/src/storages/base_storage.py#L8-L12

**Comment by Cub11k** [comment]
Tnx!
